In [84]:
print("Hello World")

Hello World


In [85]:
x=[1,2,3]
y=[1,2,3]

[a+b for a in x for b in y]

[2, 3, 4, 3, 4, 5, 4, 5, 6]

In [86]:
import numpy as np

arr=np.array([1,2,3,4,5], dtype=np.int8)

print(type(arr))
print(type(arr[1]))



<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [87]:
import math as m
m.sqrt(16)
#m.pi

4.0

In [88]:
from math import sqrt as qrt,pi as pai
qrt(25)

5.0

In [89]:
import numpy as np

arr=np.array([1,2,3,4,5], dtype=np.int8)


In [90]:


arr1=np.array([[[1,1],[2,2]],[[1,1],[2,2]]], dtype=np.int8)

print(arr1)


[[[1 1]
  [2 2]]

 [[1 1]
  [2 2]]]


In [91]:
mat1=np.zeros((5,5,5))
print(mat1)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [92]:
from package import maths as m

print(m.additions(1,8))
print(m.substractions(1,8))

9
-7


In [93]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])


print(a+b)

[5 7 9]


In [94]:
print(np.dot(a,b))



32


In [95]:
import numpy as np

# 1D array
a = np.array([1, 3, 2, 4, 5])
max_index_1d = np.argmax(a)
print(f"Index of the maximum element in 1D array: {max_index_1d}") # Output: 4

# 2D array
b = np.array([[10, 17, 25], 
              [30, 11, 27]])

# Index of the max element in the flattened array
max_index_flat = np.argmax(b)
print(f"Index of the largest element in the flattened array: {max_index_flat}") # Output: 2

# Indices along axis 0 (columns)
max_index_axis0 = np.argmax(b, axis=0)
print(f"Indices of the largest element along axis 0: {max_index_axis0}") # Output: [1 0 0]

# Indices along axis 1 (rows)
max_index_axis1 = np.argmax(b, axis=1)
print(f"Indices of the largest element along axis 1: {max_index_axis1}") # Output: [2 2]


Index of the maximum element in 1D array: 4
Index of the largest element in the flattened array: 3
Indices of the largest element along axis 0: [1 0 1]
Indices of the largest element along axis 1: [2 0]


In [96]:
import numpy as np

data_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

median_axis_0 = np.median(data_2d, axis=0) # Median of each column
median_axis_1 = np.median(data_2d, axis=1) # Median of each row

print("Median along axis 0:", median_axis_0)
print("Median along axis 1:", median_axis_1)


Median along axis 0: [4. 5. 6.]
Median along axis 1: [2. 5. 8.]


In [10]:
import numpy as np

arr1=np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))

print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [16]:
arr2=np.array([1,2,3,4,5])
arr2=arr2.reshape(1,5)

print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [22]:
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])

print(arr3)
print(type(arr3))
print(arr3.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
(2, 5)


Added for commit

In [23]:
import pandas as pd1
